---

- name: update
  dnf: 
    name: "*"
    state: latest
  become: yes

- name: Install nginx
  dnf:
    name: "nginx"
    state: present
  become: yes

- name: Start service
  systemd: 
    name: nginx
    state: started
    enabled: yes
  become: yes




